// See https://aka.ms/new-console-template for more information
Console.WriteLine("==========================================");
Console.WriteLine("nomre 1 ra vared konid");
string input1 = Console.ReadLine();
double x = Convert.ToInt32(input1);
Console.WriteLine("zarib nomre aval ra vared konid");
string n1 = Console.ReadLine();
double zarib1 = Convert.ToInt32(n1);
double nomre1 = zarib1 * x;
Console.WriteLine(nomre1);
Console.WriteLine("==========================================");
Console.WriteLine("nomre 2 ra vared konid");
string input2 = Console.ReadLine();
double U = Convert.ToInt32(input2);
Console.WriteLine("ZARIB NOMRE 2 RA VARED KONID");
String n2 = Console.ReadLine();
double zarib2 = Convert.ToInt32(n2);
double nomre2 = zarib2 * U;
Console.WriteLine(nomre2);
Console.WriteLine("==========================================");
Console.WriteLine("nomre 3 ra vared konid ");
string input3 = Console.ReadLine();
double y = Convert.ToInt32(input3);
Console.WriteLine("zarib nomre 3 ra vared konid");
string n3 = Console.ReadLine();
double zarib3 = Convert.ToInt32(n3);
double nomre3 = zarib3 * y;
Console.WriteLine(nomre3);
Console.WriteLine("==========================================");
Console.WriteLine("nomre4 ra vared konid");
string input4 = Console.ReadLine();
double s = Convert.ToInt32(input4);
Console.WriteLine("Zarib nomre4 ra vared konid ");
string n4 = Console.ReadLine();
double zarib4 = Convert.ToInt32(n4);
double nomre4 = zarib4 * s;
Console.WriteLine(nomre4);
Console.WriteLine("==========================================");
Console.WriteLine("nomre5 ra vared konid");
string input5 = Console.ReadLine();
double f = Convert.ToInt32(input5);
Console.WriteLine("zarib nomre 5 ra vared konid");
string n5 = Console.ReadLine();
double zarib5 = Convert.ToInt32(n5);
double nomre5 = zarib5 * f;
Console.WriteLine(nomre5);
Console.WriteLine("==========================================");
Console.WriteLine("nomre6 ra vared konid");
string input6 = Console.ReadLine();
double z = Convert.ToInt32(input6);
Console.WriteLine(" zarib nomre6 ra vared konid");
string n6 = Console.ReadLine();
double zarib6 = Convert.ToInt32(n6);
double nomre6 = zarib6 * z;
Console.WriteLine(nomre6);
Console.WriteLine("==========================================");
Console.WriteLine("nomre7 ra vared konud");
string input7 = Console.ReadLine();
double r = Convert.ToInt32(input7);
Console.WriteLine("zarib nomre7 ra vared konid");
string n7 = Console.ReadLine();
double zarib7 = Convert.ToInt32(n7);
double nomre7 = zarib7 * r;
Console.WriteLine(nomre7);
Console.WriteLine("==========================================");
Console.WriteLine("nomre8 ra vared konid");
string input8 = Console.ReadLine();
double d = Convert.ToInt32(input8);
Console.WriteLine("zarib nomre8 ra vared konid");
string n8 = Console.ReadLine();
double zarib8 = Convert.ToInt32(n8);
double nomre8 = zarib8 * d;
Console.WriteLine(nomre8);
Console.WriteLine("==========================================");
Console.WriteLine("nomre 9 ra vared konid");
string input9 = Console.ReadLine();
double b = Convert.ToInt32(input9);
Console.WriteLine("zarib nomre9 ra vared konid");
string n9 = Console.ReadLine();
double zarib9 = Convert.ToInt32(n9);
double nomre9 = zarib9 * b;
Console.WriteLine(nomre9);
Console.WriteLine("==========================================");
Console.WriteLine("nomre10 ra vared konid");
string input10 = Console.ReadLine();
double h = Convert.ToInt32(input10);
Console.WriteLine("zarib nomre10 ra vared konid");
string n10 = Console.ReadLine();
double zarib10 = Convert.ToInt32(n10);
double nomre10 = zarib10 * h;
Console.WriteLine(nomre10);

double miangin = (nomre1 + nomre2 + nomre3 + nomre4 + nomre5 + nomre6 + nomre7 + nomre8 + nomre9 + nomre10) / (zarib1 + zarib2 + zarib3 + zarib4 + zarib5 + zarib6 + zarib7 + zarib8 + zarib9 + zarib10);
Console.WriteLine("==========================================");
Console.WriteLine("moadel=");
Console.WriteLine( miangin);
Console.ReadKey();